### ISSUE TITLE
indexing/processing umlauts

### ISSUE THREAD

**Issue by Lokke** [swing-opensource/swingmusic#165]
looks like swing has some issues with processing german umlauts

```
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
 94%|██████████████████████████████████████████▏  |201356/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/55/Conny Chaos und die Retortenkinder - Die größte Show der Welt.mp3
 94%|██████████████████████████████████████████▎  |202193/214769Could not read file: E:/Musik/S/Sprottenrock/Chez Dose/SprottenRock - Schieß doch (DFB-Cover).wav
 95%|██████████████████████████████████████████▌  |203068/214769Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 12 - Sonntagssuff.mp3
 95%|██████████████████████████████████████████▉  |204657/214769Could not read file: E:/Musik/VA-Sampler/Kassensturz BRD Sampler/Kassensturz BRD 6/Die Kunstbanausen - Für Die Generation.wav
 96%|███████████████████████████████████████████  |205714/214769Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[08] Racey - Kitty.mp3
 96%|███████████████████████████████████████████▏ |206173/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/62/Störfacktor - Störfacktor.mp3
 96%|███████████████████████████████████████████▎ |207008/214769Could not read file: E:/Musik/D/Die Ärzte/2007 - Jazz ist Anders (Economy)/01 - Himmelblau.mp3
 97%|███████████████████████████████████████████▌ |207798/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/67/Glück Umsonst - Unbedingt all inclusive.mp3
 97%|███████████████████████████████████████████▋ |208409/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/43/WNG - Endlich glücklich.mp3
 98%|███████████████████████████████████████████▉ |209636/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/41/Kraut & Rüben - Komm doch zu uns.mp3
 99%|████████████████████████████████████████████▋|212989/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/51/Die Rote Suzuki - und täglich grüßt....mp3
100%|████████████████████████████████████████████▊|213945/214769Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/53/Kollektiver Brechreiz - Helden für einen Tag.mp3
100%|█████████████████████████████████████████████|214769/214769
Adding 214620 tracks to database
Added 214620/214769 tracks
INFO|Extracting track images ...
 27%|████████████▏                                |10257/3784412868666 ERROR: Exception on /getall/albums [GET]
Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "flask_restful\__init__.py", line 489, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restful\__init__.py", line 604, in dispatch_request
  File "app\api\getall\resources.py", line 70, in get
  File "app\utils\dates.py", line 23, in date_string_to_time_passed
OSError: [Errno 22] Invalid argument
100%|█████████████████████████████████████████████|37844/37844
INFO|Processing missing album colors ...
100%|█████████████████████████████████████████████|37844/37844
INFO|Processing missing artist colors ...
100%|█████████████████████████████████████████████|17113/17113
Loading artists... Done!
Exception in thread Thread-3 (run_periodic_scans):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "app\periodic_scan.py", line 26, in run_periodic_scans
  File "app\lib\populate.py", line 96, in __init__
  File "app\store\albums.py", line 58, in load_albums
  File "app\models\album.py", line 209, in get_date_from_tracks
OSError: [Errno 22] Invalid argument
Loading albums... INFO|Validating tracks ...
100%|█████████████████████████████████████████████|222842/222842
Found 149 new tracks
INFO|Reading files ...
  0%|                                             |0/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/57/Die Dödelsäcke - Wüstenlied.mp3
  1%|▎                                            |1/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/53/Kollektiver Brechreiz - Helden für einen Tag.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/43/shame on you Mr. Präsident - Track 30.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/68/Evil Klöten & the Dalli Dallis - Track 21.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/53/Kollateralschaden - König der Verückten.mp3
  3%|█▌                                           |5/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 06 - Makhnovtchina.mp3
Could not read file: E:/Musik/K/Kollektiver Brechreiz/2013 - Der Sinn des Lebens/Kollektiver Brechreiz - 14 - Helden für einen Tag.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/56/Gottkaiser - Rückendeckung.mp3
Could not read file: E:/Musik/L/Lärmatron/Lärmatron in besserer Quali/Lärmatron - Hollywood.wav
  6%|██▋                                          |9/149Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Prost Freunde.wav
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 04 - Verarscht.mp3
Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 04 - Deine Mudda und dein Vadda sind verwandt.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/55/Conny Chaos und die Retortenkinder - Die größte Show der Welt.mp3
  9%|███▉                                         |13/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/65/BTM - Dumm und glücklich.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[11] Racey - We Are Racey.mp3
Could not read file: E:/Musik/L/Lärmatron/Lärmatron in besserer Quali/Lärmatron - Pole Position.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/46/Drosophila - Blick zurück.mp3
 11%|█████▏                                       |17/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 10 - The Union.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/43/WNG - Endlich glücklich.mp3
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 05 - Blut.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[05] Racey - She's A Winner.mp3
 14%|██████▎                                      |21/149Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Intro.wav
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 13 - Auf die Barrikaden.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Wahre Freundschaft.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/60/Gruftrosen - Mörder von Gestern.mp3
 17%|███████▌                                     |25/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/63/Gumbles - Zu alt für Pogo.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 08 - Es ist vorbei.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/67/Glück Umsonst - Unbedingt all inclusive.mp3
Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 05 - Wo Ist Das Kind Mit Meinem Café Latte.wav
 19%|████████▊                                    |29/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 09 - Spaniens Himmel.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/49/Grätenkinder - Karlchen.mp3
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 01 - Tempes Internationale.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/68/The Schön - Therapie.mp3
 22%|█████████▉                                   |33/149Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Höllenbrut.wav
Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 02 - Ruf Mich Nicht An, Ich Tus Auch Nicht.wav
Could not read file: E:/Musik/K/Kollektiver Brechreiz/Der Sinn des Lebens/Kollektiver Brechreiz - 14 - Helden für einen Tag.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 09 - 6 Millionen.mp3
 25%|███████████▏                                 |37/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 02 - Marsch der Antifaschisten.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/41/Kraut & Rüben - Komm doch zu uns.mp3
Could not read file: E:/Musik/M/Melanie & The Secret Army/2007- Cock Sparrer We Love You/03- Bird Trouble.MP3
Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 07 - Zwar Nicht Schön, Aber Mit Liebe.wav
 28%|████████████▍                                |41/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 07 - Rote Kolonne.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/46/Die Chinesischen Glückskekse - Pornostar.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 06 - Auf die Fresse.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/53/Wilde Zeiten - Fünfsternepunks.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[07] Racey - Lay Your Love On Me.mp3
 31%|█████████████▉                               |46/149Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[01] Racey - Love's A Riot.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Gegen den Strom.wav
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 08 - Feiertag.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[10] Racey - Boy Oh Boy.mp3
Could not read file: E:/Musik/I/Incident/2009 - Navždy A Večne/15 - Incident - Sila Slobody.mp3
 34%|███████████████▍                             |51/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/59/Bad Nenndorf Boys - Laß dich nicht unterkriegen.mp3
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 04 - Der heimliche Aufmarsch.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/42/Die Böslinge - Geht`s ma net am Orsch.mp3
Could not read file: E:/Musik/S/Sprottenrock/Chez Dose/SprottenRock - Ein Stück zurück.wav
 37%|████████████████▌                            |55/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/02/Psycho Gambola - Spätvorstellung.mp3
Could not read file: E:/Musik/A/Absturtz/2007 - Linke Propaganda/Absturtz - 17 - Spaß.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Dunkle Gassen.wav
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Amok.wav
 40%|█████████████████▊                           |59/149Could not read file: E:/Musik/K/Kollektiver Brechreiz/2013 - Der Sinn des Lebens/Kollektiver Brechreiz - 11 - Die Köperfresser kommen.mp3
Could not read file: E:/Musik/A/AnalO.H.G/2000 - Hallo, wir sind`s/AnalO.H.G. - Ich Wollt Ich Wär.wav
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 09 - Wehrt Euch.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Tanz der Teufel.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/66/H.O.A. - Geh doch nach drüben.mp3
 43%|███████████████████▎                         |64/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/68/Alles auf Anfang - Scheiß Spiel.mp3
Could not read file: E:/Musik/K/Kollektiver Brechreiz/Der Sinn des Lebens/Kollektiver Brechreiz - 11 - Die Köperfresser kommen.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Jeder gegen Jeden.wav
Could not read file: E:/Musik/VA-Sampler/Kassensturz BRD Sampler/Kassensturz BRD 6/Dv Hvnd - Die Wüste Lebt.wav
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 03 - Guten Morgen Deutschland.mp3
 46%|████████████████████▊                        |69/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 11 - Mein Vater wird gesucht.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[02] Racey - Such A Night.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/62/Backstreet Noise - Ein bißchen wie H&M.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/50/Rock`n ´Roll Stromtroopers - Astrogirl.mp3
 49%|██████████████████████                       |73/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/67/Klabusterbären - Ich tanze zu Cure die ganze Nacht.mp3
Could not read file: E:/Musik/A/Ansicht X/- BassBox/Ansicht X - 09 - Lass uns Träumen.mp3
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 08 - Hasta Siempre.mp3
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 06 - Wohin wohin.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Ich steh hier.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/42/Brambilla - Restwürde.mp3
 53%|███████████████████████▊                     |79/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/51/Die Rote Suzuki - und täglich grüßt....mp3
Could not read file: E:/Musik/D/Die Ärzte/2007 - Jazz ist Anders (Economy)/01 - Himmelblau.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[03] Racey - There's A Party Going On.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/02/Supernichts - Bahnfahren macht hässlich.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/50/Ook Dat Nog - 65 min Liedchen.mp3
 56%|█████████████████████████▎                   |84/149Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[06] Racey - Some Girls.mp3
Could not read file: E:/Musik/S/Sprottenrock/Chez Dose/SprottenRock - Räggi.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/41/Nötigung - Hinter schwedischen Gardinen.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 12 - Punk Rock Zeit.mp3
Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 08 - Schmeckt Wie Laterne Ganz Unten.wav
 60%|██████████████████████████▉                  |89/149Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 06 - Ich Kam Sogar Zum Klassentreffen Zu Spät.wav
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[04] Racey - Lay Your Cards On The Table.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/53/Fliehende Stürme - Ausgeschieden.mp3
Could not read file: E:/Musik/F/Foiernacht/2016 - Kuss der Strasse/Foiernacht - Alles was war.wav
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 13 - Gemein.mp3
 63%|████████████████████████████▍                |94/149Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 03 - Which side are you on-.mp3
Could not read file: E:/Musik/A/Ansicht X/- BassBox/Ansicht X - 08 - Böse, Fies, Hundsgemein.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/60/Grölbüdels - Schöne Welt.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/43/Just Fuckin`Andy - Die Mädchen von H&M.mp3
 66%|█████████████████████████████▌               |98/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/56/Supernichts - Du und Deine scheiß FDP.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/56/Müllsch - Whish you were gone.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/40/Jesus Skins - 77 heißt grüßt Gott.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/67/Spätzledreck - Straight Depp.mp3
 68%|██████████████████████████████▊              |102/149Could not read file: E:/Musik/VA-Sampler/Kassensturz BRD Sampler/Kassensturz BRD 6/Die Kunstbanausen - Für Die Generation.wav
Could not read file: E:/Musik/A/Absturtz/2007 - Linke Propaganda/Absturtz - 11 - Träumen.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/41/Dödelhaie - Radieschen auf Frischkäse.mp3
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 05 - In Erwägung.mp3
 71%|████████████████████████████████             |106/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/62/Snorde - Zähltage.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/55/Träsh Torten Combo - Textphobie.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/49/American Tourists - Nur geträumt.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/51/b-seite - Seitdem der kleine Junge unaufhörlich weint.mp3
 74%|█████████████████████████████████▏           |110/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/43/Nevermind - Spaßmobil.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/46/Mono Für Alle - Amoklauf.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/62/Störfacktor - Störfacktor.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/43/Mumüzumundi - Was du bist.mp3
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 12 - An Rhein und Ruhr.mp3
 77%|██████████████████████████████████▋          |115/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/48/Mono Für Alle - Gewalt gegen Sachen.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[09] Racey - Rah Stateway.mp3
Could not read file: E:/Musik/R/Racey/1979 - Smash And Grab/[08] Racey - Kitty.mp3
Could not read file: E:/Musik/K/Kollektiver Brechreiz/Der Sinn des Lebens/Kollektiver Brechreiz - 06 - Nur geträumt.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/60/Civil Unrest - Viele Grüße.mp3
 81%|████████████████████████████████████▏        |120/149Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 07 - Scheiss Tag.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 04 - Equador.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Goldene Jahre.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/60/Sidetracked - Inhalte einfügen.mp3
Could not read file: E:/Musik/K/Kollektiver Brechreiz/2013 - Der Sinn des Lebens/Kollektiver Brechreiz - 06 - Nur geträumt.mp3
 84%|█████████████████████████████████████▊       |125/149Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 11 - Pervers.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/50/Bildungslücke - Europa rüstet auf.mp3
Could not read file: E:/Musik/B/Besudelt mit Stuhl/2008 - Dekolletés und Dekadenz/Betrunken im Klappstuhl - 03 - Südamerika.wav
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 02 - Das war schon immer so.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 05 - Wir sind Abgelehnt.mp3
 87%|███████████████████████████████████████▎     |130/149Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 02 - Aus Erfahrung Wut.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/46/Shit Lives On - Das Leben ist schön.mp3
Could not read file: E:/Musik/C/Commandantes/2006 - Für Brot Und Freiheit!/Commandantes - 14 - Commandantes Internatinale.mp3
Could not read file: E:/Musik/A/Abfallsozialprodukt/Keine Macht den Faschisten/Abfallsozialprodukt - § 218.mp3
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 07 - Norma.mp3
 91%|████████████████████████████████████████▊    |135/149Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 12 - Sonntagssuff.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/47/Abwärts - Terrorbeat.mp3
Could not read file: E:/Musik/S/Sprottenrock/Chez Dose/SprottenRock - Die Zeit läuft.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/50/Delikät - Joe Ackermann.mp3
 93%|█████████████████████████████████████████▉   |139/149Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/60/Die KEine Ahnung - Märchenwald.mp3
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 11 - Endstation.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/47/Jeunesse Apatrude - Düre realite.mp3
Could not read file: E:/Musik/A/Abgelehnt/Die Krone der Schöpfung/Abgelehnt - 10 - Meine Zukunft.mp3
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/56/Lükopodium - Überwachungsstaat.mp3
Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Antisocial.wav
 97%|███████████████████████████████████████████▊ |145/149Could not read file: E:/Musik/R/Restrisiko (Oi!Punk, Göttingen)/2021 - Höllenbrut/Restrisiko - Auf Wiedersehen.wav
Could not read file: E:/Musik/VA-Sampler/Plastic Bomb Sampler/62/2ter Frühling - Voll im Leben.mp3
Could not read file: E:/Musik/S/Sprottenrock/Chez Dose/SprottenRock - Schieß doch (DFB-Cover).wav
Could not read file: E:/Musik/A/AEW - Aus Erfahrung Wut/1994 - Widerstand ist schön!/AEW - 14 - Brutal aus Angst vor diesem Land.mp3
100%|█████████████████████████████████████████████|149/149
Added 0/149 tracks
INFO|Extracting track images ...
100%|█████████████████████████████████████████████|97/97
INFO|Processing missing album colors ...
100%|█████████████████████████████████████████████|221/221
INFO|Processing missing artist colors ...
100%|█████████████████████████████████████████████|17113/17113
Loading artists... Done!
Exception in thread Thread-1754 (run_populate):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "app\api\settings.py", line 235, in run_populate
  File "app\lib\populate.py", line 96, in __init__
  File "app\store\albums.py", line 58, in load_albums
  File "app\models\album.py", line 209, in get_date_from_tracks
OSError: [Errno 22] Invalid argument

```

**Comment by cwilvx** [comment]
Hello @Lokke 

Thanks for opening this issue. 

The problem is not the umlauts (if they were the problem, we should be getting unicode errors). It looks like it's something to do with album dates.

I've edited your original comment to format the traceback. I'll look into it the issue.

Thanks.

**Comment by cwilvx** [comment]
@Lokke 

This issue has been fixed and pushed to latest. You can redownload the latest release. Let me know whether it fixed the problem.

Here's a link to the release:
https://github.com/swing-opensource/swingmusic/releases/tag/v1.4.6

If you're using Docker, you can pull the latest tag.
```
docker pull ghcr.io/swing-opensource/swingmusic:latest
```

Enjoy!
