### ISSUE TITLE
Issue on getting albums

### ISSUE THREAD

**Issue by tcsenpai** [swing-opensource/swingmusic#170]
When I try to load all the albums:

`
22151 ERROR: Exception on /getall/albums [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1484, in full_dispatch_request
  File "flask/app.py", line 1469, in dispatch_request
  File "flask_restful/__init__.py", line 489, in wrapper
  File "flask/views.py", line 109, in view
  File "flask_restful/__init__.py", line 604, in dispatch_request
  File "app/api/getall/resources.py", line 70, in get
  File "app/utils/dates.py", line 26, in date_string_to_time_passed
  File "pendulum/__init__.py", line 211, in now
  File "pendulum/tz/__init__.py", line 60, in local_timezone
  File "pendulum/tz/local_timezone.py", line 35, in get_local_timezone
  File "pendulum/tz/local_timezone.py", line 63, in _get_system_timezone
  File "pendulum/tz/local_timezone.py", line 242, in _get_unix_timezone
RuntimeError: Unable to find any timezone configuration

`

The fix is:

`docker exec -it [container_id]
apt update && apt install -y tzdata`

Including this in the original image should be sufficient

**Comment by cwilvx** [comment]
@tcsenpai 

Thank you for the suggestion. I've added the install command in the `Dockerfile` in https://github.com/swing-opensource/swingmusic/commit/9bf005668b21a1600997153e85745959c2b2eaed like this:

```dockerfile
RUN apt update && apt install -y tzdata
```

Is that what you were suggesting? Will that work?

**Comment by tcsenpai** [comment]
@cwilvx exactly, in my experience it worked

I'd suggest to execute that command as a "post install" thing , to avoid updating and upgrading packages you may need in a different version

**Comment by cwilvx** [comment]
@tcsenpai 

I'm not familiar with Docker. Can you elaborate or provide an example of what you mean by post install?

You can take a look at the `Dockerfile` here:

https://github.com/swing-opensource/swingmusic/blob/master/Dockerfile

**Comment by tcsenpai** [comment]
> @tcsenpai
> 
> I'm not familiar with Docker. Can you elaborate or provide an example of what you mean by post install?
> 
> You can take a look at the `Dockerfile` here:
> 
> https://github.com/swing-opensource/swingmusic/blob/master/Dockerfile

With the modifications you did, it works . Thanks, closed as solved
